version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: portfolio-nico-db
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql
    command:
      # prettier-ignore
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=portfolio
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
volumes:
  db-store:
